# This is a basic workflow to help you get started with Actions

name: typescript

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [ push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:14-alpine
    #     env:
    #       POSTGRES_DB: rlly-test
    #       POSTGRES_PASSWORD: password
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      # Install dependencies
      - run: yarn install

      # # Run unit tests
      # - run: yarn jest
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@localhost:5432/rlly-test

      # Run the type checking against the whole repo
      - run: yarn tsc --noEmit
